# Generated by Django 4.2.7 on 2023-11-08 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition_Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('total_fats', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('serving_size', models.CharField(max_length=75)),
                ('ingredients', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('directions', models.TextField()),
                ('dish_types', models.ManyToManyField(to='main_app.dish_type')),
                ('nutrition_label', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nutrition_label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Posted')),
                ('rating', models.CharField(choices=[('1', "I wouldn't trust them running a bath, let alone a restaurant."), ('2', "This isn't a recipe, this is a mistake."), ('3', "They're not afraid to take risks, and they're not afraid to fail; that's how you succeed."), ('4', 'I believe that if they worked hard, stay focused, and never give up, they can achieve anything.'), ('5', 'Chefs are like magicians, they transform raw ingredients into something magical.')], default='3', max_length=1)),
                ('comment', models.TextField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe')),
            ],
        ),
    ]
