# Generated by Django 4.2.7 on 2023-11-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dish_types',
        ),
        migrations.DeleteModel(
            name='Dish_Type',
        ),
    ]
