# Generated by Django 4.2.6 on 2023-11-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition_label',
            name='added_sugars',
        ),
    ]
