# Generated by Django 4.2.7 on 2023-11-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_recipes_recipe_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Posted')),
                ('rating', models.CharField(choices=[('1', "I wouldn't trust them running a bath, let alone a restaurant."), ('2', "This isn't a recipe, this is a mistake."), ('3', "They're not afraid to take risks, and they're not afraid to fail; that's how you succeed."), ('4', 'I believe that if they worked hard, stay focused, and never give up, they can achieve anything.'), ('5', 'Chefs are like magicians, they transform raw ingredients into something magical.')], default="They're not afraid to take risks, and they're not afraid to fail; that's how you succeed.", max_length=1)),
                ('comment', models.TextField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
