# Generated by Django 4.2.7 on 2023-11-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_nutrient_remove_nutrition_label_cholesterol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition_label',
            name='cholesterol',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='protein',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='sodium',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='total_carbs',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='total_fats',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutrition_label',
            name='yield_value',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_size',
            field=models.FloatField(default=1.0),
        ),
    ]
