# Generated by Django 4.2.6 on 2023-11-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_nutrition_label_cholesterol_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition_label',
            name='cholesterol_unit',
            field=models.CharField(default='mg'),
        ),
    ]
