# Generated by Django 4.2.6 on 2023-11-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_nutrition_label_cholesterol_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition_label',
            name='total_fat_unit',
            field=models.CharField(default='g'),
        ),
    ]
