# Generated by Django 4.2.7 on 2023-11-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_nutrition_label_cholesterol_nutrition_label_protein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition_label',
            name='yield_value',
            field=models.FloatField(default=1.0),
        ),
    ]
