# Generated by Django 4.2.7 on 2023-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', "I wouldn't trust them running a bath, let alone a restaurant."), ('2', "This isn't a recipe, this is a mistake."), ('3', "They're not afraid to take risks, and they're not afraid to fail; that's how you succeed."), ('4', 'I believe that if they worked hard, stay focused, and never give up, they can achieve anything.'), ('5', 'Chefs are like magicians, they transform raw ingredients into something magical.')], default='3', max_length=1),
        ),
    ]
