# Generated by Django 4.2.7 on 2023-11-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_nutrition_label_yield_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition_label',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nutrition_label',
            name='cholesterol',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nutrition_label',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nutrition_label',
            name='sodium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nutrition_label',
            name='total_carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nutrition_label',
            name='total_fats',
            field=models.FloatField(default=0.0),
        ),
    ]
