# Generated by Django 4.2.6 on 2023-11-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_nutrition_label_total_fat_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition_label',
            name='dietary_fiber_unit',
            field=models.CharField(default='g'),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='protein_unit',
            field=models.CharField(default='g'),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='saturated_fat_unit',
            field=models.CharField(default='g'),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='sodium_unit',
            field=models.CharField(default='mg'),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='total_carbs_unit',
            field=models.CharField(default='g'),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='total_sugars_unit',
            field=models.CharField(default='g'),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='trans_fat_unit',
            field=models.CharField(default='g'),
        ),
    ]
