# Generated by Django 4.2.7 on 2023-11-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition_Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('total_fats', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition_label',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nutrition_label'),
        ),
    ]
