# Generated by Django 4.2.6 on 2023-11-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_20231110_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition_label',
            old_name='total_fats',
            new_name='total_fat',
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='added_sugars',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='dietary_fiber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='saturated_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='total_sugars',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nutrition_label',
            name='trans_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nutrition_label',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
    ]
